import type { DemoConfig } from "@/components/DemoSite";

export const demoConfigs: Record<string, DemoConfig> = {
  "luxury-restaurant": {
    brand: "Saffron & Smoke",
    tagline: "Modern bistro · Reservations open nightly.",
    industry: "Hospitality",
    hero: {
      eyebrow: "Modern fine dining",
      title: "A taste of |elegance| reimagined.",
      subtitle: "Seasonal tasting menus, hand-curated wines, and an intimate dining room designed for unforgettable evenings.",
      cta: "Reserve a Table",
      image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    },
    accent: { from: "amber-400", to: "rose-500" },
    about: {
      title: "Crafted with intention, served with soul.",
      body: "Saffron & Smoke is the vision of Chef Alessandro Conti, blending Mediterranean roots with modern technique. Every plate tells a story — sourced from local farms, finished over open flame, and served in a room designed to slow time down.",
      bullets: ["Michelin-recommended kitchen", "Sourced from local farms", "Curated wine cellar of 200+ labels", "Private dining for up to 24 guests"],
    },
    services: [
      { title: "À La Carte Dining", desc: "An evolving seasonal menu served Tuesday through Sunday evenings." },
      { title: "Chef's Tasting", desc: "Seven-course experience paired with sommelier-selected wines." },
      { title: "Private Events", desc: "Curated menus and full-venue buyouts for milestone occasions." },
      { title: "Catering", desc: "Off-premise catering for weddings, corporate, and intimate gatherings." },
    ],
    contact: { email: "reservations@saffronsmoke.com", phone: "+1 (415) 555-0182", address: "212 Hayes Street, San Francisco, CA" },
    testimonial: { quote: "The most thoughtful dining experience I've had in years. Every detail mattered.", author: "Elena Voss", role: "Food critic, Plate Magazine" },
  },
  "real-estate": {
    brand: "Lumen Estates",
    tagline: "Luxury property, intelligently presented.",
    industry: "Real Estate",
    hero: {
      eyebrow: "Premium properties",
      title: "Find the |home| you'll never leave.",
      subtitle: "We represent the most distinctive properties across coastal California — from architectural icons to modern beachside retreats.",
      cta: "Browse Listings",
      image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    },
    accent: { from: "sky-400", to: "indigo-500" },
    about: {
      title: "A boutique brokerage with a global eye.",
      body: "Lumen represents discerning buyers and sellers from Los Angeles to Lisbon. Our team blends design literacy, market data, and a network spanning twelve countries to deliver outcomes that go beyond the transaction.",
      bullets: ["$1.2B+ in lifetime sales", "Average list-to-sale ratio of 99.4%", "20+ language-fluent agents", "White-glove relocation services"],
    },
    services: [
      { title: "Buyer Representation", desc: "Curated property matches with off-market access and full-cycle advisory." },
      { title: "Listing & Marketing", desc: "Cinematic media, global syndication, and architectural staging." },
      { title: "Investment Advisory", desc: "Portfolio strategy and 1031 exchanges for sophisticated investors." },
      { title: "Property Management", desc: "Concierge management for second homes and short-term rentals." },
    ],
    contact: { email: "hello@lumenestates.com", phone: "+1 (310) 555-2244", address: "1801 Avenue of the Stars, Los Angeles, CA" },
    testimonial: { quote: "Lumen sold our Malibu home in nine days, fifteen percent above ask. Their marketing is in a different league.", author: "Daniel & Mara Aoki", role: "Sellers, Carbon Beach" },
  },
  "healthcare": {
    brand: "Vitalis Care",
    tagline: "Compassionate, modern medicine.",
    industry: "Healthcare",
    hero: {
      eyebrow: "Primary & specialty care",
      title: "Healthcare that |understands| you.",
      subtitle: "Integrated primary care, mental health, and wellness — delivered by a team that takes the time to know you.",
      cta: "Book Appointment",
      image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80",
    },
    accent: { from: "teal-400", to: "emerald-500" },
    about: {
      title: "A different kind of clinic.",
      body: "Vitalis was founded by a team of physicians who believed primary care could feel personal again. Same-day appointments, longer visits, integrated specialists, and a patient portal that actually works.",
      bullets: ["Same-day appointments available", "Board-certified physicians", "Integrated mental health team", "HIPAA-compliant patient portal"],
    },
    services: [
      { title: "Primary Care", desc: "Comprehensive adult and family medicine with annual wellness planning." },
      { title: "Mental Health", desc: "Therapy and psychiatry appointments — in-person or telehealth." },
      { title: "Women's Health", desc: "OB-GYN services, fertility consultation, and hormone health." },
      { title: "Preventive Care", desc: "Advanced labs, screenings, and longevity-focused programs." },
    ],
    contact: { email: "care@vitalishealth.com", phone: "+1 (646) 555-7790", address: "445 Park Avenue, New York, NY" },
    testimonial: { quote: "The first clinic where I felt my doctor actually had time for me. Booking is effortless.", author: "Priya Shah", role: "Patient since 2024" },
  },
  "business-coach": {
    brand: "Mindshift Academy",
    tagline: "Coaching for ambitious operators.",
    industry: "Coaching",
    hero: {
      eyebrow: "Executive coaching",
      title: "Build the business — and the |life| — you actually want.",
      subtitle: "1:1 coaching, cohort programs, and frameworks used by 400+ founders and senior operators across 22 countries.",
      cta: "Apply for Coaching",
      image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80",
    },
    accent: { from: "fuchsia-500", to: "purple-600" },
    about: {
      title: "Meet your coach: Naomi Becker.",
      body: "Former VP at two unicorn startups turned executive coach, Naomi has helped founders raise over $400M and operators 3x their income while reclaiming their time. Her work blends behavioral science with practical operating systems.",
      bullets: ["Featured in Forbes & Inc.", "400+ clients across 22 countries", "ICF-certified executive coach", "Cohort & private coaching tracks"],
    },
    services: [
      { title: "1:1 Coaching", desc: "Twelve-week private coaching engagement with weekly sessions and async access." },
      { title: "Founder Cohort", desc: "Eight-week group program for early-stage founders building their first team." },
      { title: "Executive Cohort", desc: "Senior operator cohort focused on leverage, hiring, and energy management." },
      { title: "Corporate Workshops", desc: "Half-day and full-day workshops for leadership teams." },
    ],
    contact: { email: "hello@mindshift.academy", phone: "+1 (512) 555-3311", address: "Remote · HQ in Austin, TX" },
    testimonial: { quote: "Naomi helped me restructure my agency and double take-home pay in six months. The frameworks are gold.", author: "Marcus Lin", role: "Founder, North & Co." },
  },
  "tech-startup": {
    brand: "Orbit Labs",
    tagline: "AI-native operations, simplified.",
    industry: "SaaS / Tech",
    hero: {
      eyebrow: "AI workflow platform",
      title: "Ship operations |10x faster| with AI agents.",
      subtitle: "Orbit gives ops teams a no-code surface to build, deploy, and monitor AI agents that handle the work — across 80+ apps.",
      cta: "Start Free Trial",
      image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1200&q=80",
    },
    accent: { from: "cyan-400", to: "blue-600" },
    about: {
      title: "Built by operators, for operators.",
      body: "Orbit was started by a team that spent a decade automating ops at Stripe, Notion, and Ramp. We're building the AI workflow layer modern teams actually deserve — fast, observable, and friendly to non-engineers.",
      bullets: ["YC-backed (W25)", "SOC 2 Type II certified", "80+ native app integrations", "Used by 1,200+ teams worldwide"],
    },
    services: [
      { title: "AI Agents", desc: "Pre-built agents for sales ops, customer support, and finance — fully customizable." },
      { title: "Workflow Builder", desc: "Drag-and-drop builder with built-in observability and version control." },
      { title: "Integrations", desc: "Native connectors for Slack, HubSpot, Salesforce, Notion, and 80+ more." },
      { title: "Enterprise", desc: "SSO, audit logs, custom data residency, and dedicated success." },
    ],
    contact: { email: "team@orbit.dev", phone: "+1 (415) 555-9981", address: "548 Market Street, San Francisco, CA" },
    testimonial: { quote: "Orbit replaced four manual workflows in our first month. Our ops team is genuinely happier.", author: "Sofía Reyes", role: "Head of RevOps, Helix" },
  },
  "consulting": {
    brand: "North & Co.",
    tagline: "Strategy for the next decade of growth.",
    industry: "Consulting",
    hero: {
      eyebrow: "Management consulting",
      title: "Strategy that actually |moves the needle|.",
      subtitle: "We partner with mid-market leaders to unlock growth, transform operations, and build durable advantage in a faster-moving world.",
      cta: "Start a Project",
      image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=80",
    },
    accent: { from: "violet-500", to: "indigo-600" },
    about: {
      title: "Senior strategists. No junior bait-and-switch.",
      body: "North was founded by ex-McKinsey and BCG partners who got tired of the pyramid model. Every engagement is led — and delivered — by senior people. We move fast, we tell the truth, and we stay until the work works.",
      bullets: ["Senior-led engagements", "Avg. 4.9/5 client satisfaction", "Industries: SaaS, FinTech, Healthcare", "Global team across 6 cities"],
    },
    services: [
      { title: "Growth Strategy", desc: "Market entry, GTM, and pricing transformations that compound." },
      { title: "Operations", desc: "Org design, process redesign, and cost optimization." },
      { title: "Digital & AI", desc: "AI roadmaps and digital transformation for mid-market leaders." },
      { title: "M&A Advisory", desc: "Diligence, integration, and value creation planning." },
    ],
    contact: { email: "engage@northco.com", phone: "+1 (212) 555-0440", address: "350 5th Avenue, New York, NY" },
    testimonial: { quote: "North helped us reposition for enterprise and grow ARR 3x in 18 months. Senior horsepower, no fluff.", author: "Hannah Brouwer", role: "CEO, Stagepost" },
  },
};

export const portfolioList = [
  { slug: "luxury-restaurant", name: "Saffron & Smoke", industry: "Luxury Restaurant", desc: "Reservations and tasting menus for a modern bistro.", grad: "from-amber-400/40 to-rose-500/40" },
  { slug: "real-estate", name: "Lumen Estates", industry: "Real Estate", desc: "Luxury property platform with cinematic listings.", grad: "from-sky-400/40 to-indigo-500/40" },
  { slug: "healthcare", name: "Vitalis Care", industry: "Healthcare Clinic", desc: "Patient portal with online appointment booking.", grad: "from-teal-400/40 to-emerald-500/40" },
  { slug: "business-coach", name: "Mindshift Academy", industry: "Business Coach", desc: "Coaching site with cohort & 1:1 application flow.", grad: "from-fuchsia-500/40 to-purple-600/40" },
  { slug: "tech-startup", name: "Orbit Labs", industry: "Technology Startup", desc: "AI workflow product site with trial signup.", grad: "from-cyan-400/40 to-blue-600/40" },
  { slug: "consulting", name: "North & Co.", industry: "Consulting Agency", desc: "Strategy-led consulting brand with lead intake.", grad: "from-violet-500/40 to-indigo-600/40" },
] as const;
